'use client';

import {
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronLeft,
  X,
  Calendar,
  Info,
  Check,
  Minus,
  Settings,
  Share2,
  Barcode,
  Search,
  Plus,
  TrendingUp,
  SlidersHorizontal,
  ArrowLeftRight,
  RefreshCw,
  ArrowRight,
  Ban,
  MoreVertical,
  Trash2,
  Eye,
  TrainFront,
  Warehouse,
  MoveRight,
  PackagePlus,
  PackageMinus,
  Download,
  Filter,
  ChevronsDownUp,
  List,
  Component,
  type LucideIcon,
} from 'lucide-react';

const MAP: Record<string, LucideIcon> = {
  ArrowDropDown: ChevronDown,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  ExpandMore: ChevronDown,
  ChevronUp: ChevronUp,
  Close: X,
  CalendarMonth: Calendar,
  Info: Info,
  Check: Check,
  Remove: Minus,
  Settings: Settings,
  AccountTree: Share2,
  Barcode: Barcode,
  Search: Search,
  Add: Plus,
  TrendingUp: TrendingUp,
  Tune: SlidersHorizontal,
  SwapHoriz: ArrowLeftRight,
  Cycle: RefreshCw,
  ArrowRight: ArrowRight,
  Block: Ban,
  MoreVert: MoreVertical,
  Delete: Trash2,
  View: Eye,
  Train: TrainFront,
  Warehouse: Warehouse,
  MoveRight: MoveRight,
  AssemblyOn: PackagePlus,
  AssemblyOff: PackageMinus,
  Download: Download,
  Filter: Filter,
  UnfoldLess: ChevronsDownUp,
  List: List,
  Component: Component,
};

export function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const Cmp = MAP[name] || Info;
  return <Cmp size={size} strokeWidth={2} aria-hidden focusable={false} style={{ display: 'block' }} />;
}
